#---
#platform: linux
#
#image_resource:
#  type: docker-image
#  source:
#    repository: pivotalservices/docker-concourse-cf-tools
#    tag: "latest"
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk

inputs:
- name: concoursedemo

outputs:
- name: app-manifest-output

run:
  path: concoursedemo/ci/tasks/app-manifest-prep
