groups:
- name: main
  jobs:
  - deploy-app

resources:
- name: concourse-sample
  type: git
  source:
    branch: master
    uri: https://github.com/Leisureroad/concoursedemo.git
- name: PWS
  type: cf
  source:
    api: {{pws-api}}
    organization: {{pws-organization}}
    username: {{deploy-username}}
    password: {{deploy-password}}
    skip_cert_check: true
    space: {{pws-space}}

jobs:
- name: deploy-app
  serial: true
  public: true
  plan:
  - get: concourse-sample
    trigger: true
  - task: prepare-manifest
    file: concoursedemo/ci/tasks/app-manifest-prep.yml
  - put: PWS
    params:
      manifest: app-manifest-output/manifest.yml
      path: ./